### ISSUE TITLE
Cancel throws exception

### ISSUE THREAD

**Issue by ralph-bergmann** [roman-yerin/native_qr#1]
When the user cancels a scan, an exception is thrown. I'm unsure if this is good behavior because canceling is an allowed operation and should not throw an exception.

see https://github.com/roman-yerin/native_qr/blob/trunk/android/src/main/kotlin/team/ion/native_qr/NativeQrPlugin.kt#L40

**Comment by ralph-bergmann** [comment]
At least you should make a difference between a canceled scan and a scan with a failure. Currently, both are throwing an exception, and both have the same message "canceled".

**Comment by roman-yerin** [comment]
That's because of the oversimplified Flutter plugin interface.

> Currently, both are throwing an exception, and both have the same message "canceled".

You're right.

**Comment by ralph-bergmann** [comment]
At least with [Pigeon](https://docs.flutter.dev/platform-integration/platform-channels#pigeon-example) you can implement some return Types like: `ScanResult`, `ScanCanceld` and `ScanFailure`.

**Comment by roman-yerin** [comment]
Thanks for your suggestion, Ralph, I appreciate it.
As some people asked to implement barcodes and non-string raw QR codes, your proposal is highly likely a step into the same way.

**Comment by ralph-bergmann** [comment]
According to [How to build a package in Dart](https://youtu.be/8V_TLiWszK0?t=152) you have to increase the major number of the version number because it is an API breaking change ;-)
