### ISSUE TITLE
Add a feature to implement in custom ui ?

### ISSUE THREAD

**Issue by l4km47** [roman-yerin/native_qr#2]
hay i just found your libry is neat and i just need to is it possible to add qr reader to custom ui. and also without that google logos?

**Comment by roman-yerin** [comment]
There are many package on pub.dev that fit your needs. native_qr is a wrapper around the NATIVE interfaces provided by the platforms: iOS and Android.

**Comment by l4km47** [comment]
thank you for response. any of those not fast as google ml
